# Import necessary modules from Django
from django.db import models
from django.contrib.auth.models import User



# Define your custom model named ChatBot
class ChatBot(models.Model):

    # Define a ForeignKey relationship with the built-in User model
        user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)  

    # Define a CharField to store the user's input text with a maximum length of 500 characters
        input_text = models.CharField(max_length=500)

    # Define a TextField to store the output generated by the Gemini chatbot (nullable and blank allowed)
        output_text = models.TextField(blank=True, null=True,related_name="Geminiuser")

    # Define a DateTimeField to store the timestamp when the record is created (auto-generated)
        timestamp = models.DateTimeField(auto_now_add=True,blank=True, null=True,)
 
    # Define a human-readable string representation for the ChatBot model
        
    # Return the user's input text as the string representation


   
 
        def __str__(self):
          return self.input_text 