# Import necessary modules from Django
from django.db import models
from django.contrib.auth.models import User



# Define your custom model named ChatBot

    # Define a ForeignKey relationship with the built-in User model
    # Define a CharField to store the user's input text with a maximum length of 500 characters
    # Define a TextField to store the output generated by the Gemini chatbot (nullable and blank allowed)
    # Define a DateTimeField to store the timestamp when the record is created (auto-generated)

    # Define a human-readable string representation for the ChatBot model
    # Return the user's input text as the string representation


